### 최신 블록 조회
GET http://localhost:8001/api/v1/block/latest

### 노드 상태 조회
GET http://localhost:8000/api/v1/status

### 노드 상태 조회
GET http://localhost:8001/api/v1/status

### 블록 목록 조회
GET http://localhost:8000/api/v1/blocks

### 포트 8000
GET http://localhost:8001/api/v1/block/height/10

### 블록 해시로 조회
GET http://localhost:8000/api/v1/block/hash/9fb357de59ad40056d8136af1e8eef2d38fcf2bdb596d184fb5dd162bf2e6142

### 블록 목록 (페이지네이션)
GET http://localhost:8000/api/v1/blocks?page=1&limit=10

### 트랜잭션 조회
GET http://localhost:8000/api/v1/tx/9ccc799f6931ab065ecd9feed0ca75ca09d3196a3001540b90b2846309606344

### 주소 잔액 조회
GET http://localhost:8000/api/v1/address/01b2542a9097399d94a1875d125c38bbed39fa12/balance

### 주소 UTXO 조회
GET http://localhost:8000/api/v1/address/af6736b1d7b01ac01e06da7f8fc3b83a480d6cdf/utxo

### 멤풀 조회
GET http://localhost:8000/api/v1/mempool/list

### 컨센서스 상태 조회
GET http://localhost:8000/api/v1/consensus/status

### 네트워크 통계 조회
GET http://localhost:8000/api/v1/stats

### P2P 피어 목록 조회
GET http://localhost:8000/api/v1/p2p/peers

### P2P 상태 조회
GET http://localhost:8006/api/v1/p2p/status

### 새 계정 생성
POST http://localhost:8000/api/v1/wallet/account/new

### 지갑 계정 목록 조회 - 새 계정 생성 통해 만든 계정
GET http://localhost:8000/api/v1/wallet/accounts
